- src/java.base/share/classes/java/util/Formatter.java
I noticed this when putting together
https://github.com/eisop/jdk/pull/29.
> Add one more missing `@Nullable` annotation to `Formatter`.

- src/java.base/share/classes/java/util/stream/Stream.java
I could see an argument for doing further work to declare the _type
parameter bound_ as _non_-`@Nullable`: The method can't be used to
create a `Stream` that ever contains `null`, so it would make some sense
to let it create only a `Stream<@NonNull Foo>`. Part of the question in
my mind is whether it would be good or bad for us to push users who have
a `Stream<E>` to write `Stream<@NonNull E>` if `E` is declared as `<E
extends @Nullable Object>`.
I don't know exactly what I think, so I'd like to at least land the
parameter change. If you have a preference for the type parameter, I can
make that change here and in a subsequent eisop PR.
> Annotate the parameter of `Stream.ofNullable` as `@Nullable`.

- src/java.base/share/classes/java/util/concurrent/ScheduledThreadPoolExecutor.java
@eamonnmcmanus pointed out that this was missing an import for its
existing usage of `@Nullable`. That's [my
mistake](https://github.com/jspecify/jdk/commit/f9b68aa4e118e0857ef08c2cb6b52f7432a2cceb),
and it's a mistake I've made before, but this is at least the only
current occurrence:
```
git grep -l @Nullable | xargs grep -L 'import.*Nullable;'
git grep -l @NullMarked | xargs grep -L 'import.*NullMarked;'
```
(Ideally we'd have CI to catch that mistake, as well as another mistake
I've at least come close to making, which is using the old package
name....)
Anyway, while I was fixing that, I figured I'd annotate the rest of the
class.
(As usual, I skipped a non-publicly-visible class, `DelayedWorkQueue`.)
> Annotate `ScheduledThreadPoolExecutor`.

- src/java.base/share/classes/java/util/Collections.java
- src/java.base/share/classes/java/util/ServiceLoader.java
- src/java.base/share/classes/java/util/stream/Collectors.java
- src/java.base/share/classes/java/util/stream/Stream.java
We've declared those classes' type parameters as having a bound of
`@NonNull Object`, as discussed in
https://github.com/jspecify/jspecify/issues/78. This PR changes type
arguments inside the JDK to be inside that bound.
eisop and typetools, by contrast, use a bound of `@Nullable Object`,
which they "undo" with `@NonNull T` on methods like `Class.newInstance`.
Thus, they don't need or want a change like this one. (That said, they
don't _universally_ use `@Nullable Object` as the bound in "cases like
this," so it's possible that they'd feel that a particular API, maybe
`ServiceLoader`, would be simpler with a non-nullable bound. Or, if not,
they may wish to use `@NonNull S` at the use sites.)
(The complicated API in this PR is `ServiceLoader`. I do see some docs
that suggest that …
> Make type arguments to `Class` and `Optional` non-nullable.

- src/java.base/share/classes/java/util/Objects.java
The existing approach follows the Checker Framework philosophy, under
which passing `null` for a `@Nullable` parameter should never lead to a
`NullPointerException`. (Compare `Method.invoke`, whose "receiver" _and_
"arguments" parameters are declared as non-nullable by the Checker
Framework, even though some callers _can_ pass `null` for the "receiver"
and some _must_ pass `null` for some of the arguments.)
The JSpecify thinking has moved in the direction of saying that, if
`null` should ever be permitted for a parameter, then the parameter
should be declared with a type that includes `null`. And we know that
many callers pass `null` for the second parameter. Here's an imaginary
such caller:
```java
for (Key key : union(map1.keySet(), map2.keySet()) {
Value value = …
```
> Allow a `@Nullable` value for the second parameter of `requireNonNullElse`.

- src/java.base/share/classes/java/util/ArrayList.java
- src/java.base/share/classes/java/util/List.java
- src/java.base/share/classes/java/util/Vector.java
- src/java.base/share/classes/java/util/concurrent/CopyOnWriteArrayList.java
This has always struck me as a weird feature, but people use it, and it
"works" in the sense of "does not cause NPE" (though it may cause
CCE...). I see both calls to `sort(null)` and calls like
`sort(priorityQueue.comparator())` (which _might_ be `null`;
[example](https://github.com/google/guava/blob/e82e2a2c07c68108f318958ee0355cc835c97743/guava-testlib/src/com/google/common/collect/testing/testers/SortedSetNavigationTester.java#L57)).
And while I prefer a world in which methods like `comparator()` never
return `null`, as we arranged for [in
`SortedMultiset`](https://guava.dev/SortedMultiset#comparator()), there
are apparently [downsides](https://github.com/google/guava/issues/6187)
to using a `Comparator` that implements natural order rather than using
`null`.
Is any of that …
> Annotate the parameter of `List.sort` as `@Nullable`.

- src/java.base/share/classes/java/util/HashMap.java
- src/java.base/share/classes/java/util/Hashtable.java
- src/java.base/share/classes/java/util/Map.java
- src/java.base/share/classes/java/util/concurrent/ConcurrentHashMap.java
- src/java.base/share/classes/java/util/concurrent/ConcurrentMap.java
- src/java.base/share/classes/java/util/concurrent/ConcurrentSkipListMap.java
1. Add `@Nullable` to the method return type and to the "return-type" type
argument of `remappingFunction`.
\
We had been trying to get by without, requiring users to suppress where
needed. But our philosophy has shifted more toward "If you want to be
able to put null in or get null out, then it needs to be `@Nullable`."
\
This change brings us closer to upstream, which uses `@PolyNull`.
2. Add `@NonNull` to `value` parameter and to the "input" types argument of
`remappingFunction`.
> Improve `Map.merge` annotations.

- src/java.base/share/classes/java/io/PrintWriter.java
The class appears to have zero documentation about what happens to this
field, unless you count that `close()` ["releases any system resources
associated with
it"](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/io/PrintWriter.html#close())
(and I note that that Javadoc, while it appears in `PrintWriter.java`,
is exactly the same as the more general Javadoc on `Closeable`).
But our J2KT folks noticed that they need to make the field `@Nullable`
so that their implementation (which I assume is meant to be
behavior-compatible with the JDK implementation) works under Kotlin.
That implementation (like the JDK's) assigns `null` to the field during
`close()`. That's easy to observe:
```java
import java.io.ByteArrayOutputStream;
import java.io.PrintWriter;
class PrintWriterOut …
```
> Annotate `PrintWriter.out` as `@Nullable`.

- src/java.base/share/classes/java/util/Hashtable.java
- src/java.base/share/classes/java/util/concurrent/ConcurrentHashMap.java
- src/java.base/share/classes/java/util/concurrent/ConcurrentMap.java
- src/java.base/share/classes/java/util/concurrent/ConcurrentSkipListMap.java
It's redundant there, since the value type is already non-nullable.
I overlooked this in https://github.com/jspecify/jdk/pull/14 and noticed
it only later in https://github.com/eisop/jdk/pull/45.
> Omit `@NonNull` from `merge` in maps that reject null values.

- src/java.base/share/classes/java/util/concurrent/PriorityBlockingQueue.java
- Make the constructor's comparator parameter nullable.
- Make the comparator accessor's return type nullable.
- Express that `toArray()` never contains nulls.
Compare the similar work for `PriorityQueue` in
https://github.com/jspecify/jdk/pull/17
> Improve annotations in `PriorityBlockingQueue`.

- src/java.xml/share/classes/org/w3c/dom/Node.java
The specification is a bit unclear, but it  seems to imply that null is OK. The implementation also behaves that way. Also, having `getNodeValue` return `@Nullable String` but `setNodeValue` take just `String` means that Kotlin doesn't recognize them as a get/set pair so you can't write `node.nodeValue = whatever`.
> Allow `Node.setNodeValue` to be called with a null argument.

- src/java.base/share/classes/java/util/concurrent/ConcurrentSkipListMap.java
When reviewing https://github.com/eisop/jdk/pull/51 I noticed that there is a syntax error in #19. This PR fixes that error.
> Fix type annotation syntax

- src/java.base/share/classes/java/util/concurrent/ConcurrentSkipListMap.java
Despite what I'd claimed in https://github.com/jspecify/jdk/pull/19, I
didn't make the signatures full match those in `Map`. I discovered this
as I was putting together https://github.com/eisop/jdk/pull/51.
> Add missing `@Nullable` annotation in `ConcurrentSkipListMap.compute`.

- src/java.base/share/classes/java/util/concurrent/atomic/AtomicReferenceFieldUpdater.java
My initial reaction was that this was similar to `ThreadLocal` and to
`AtomicReference`+`AtomicReferenceArray`
(https://github.com/jspecify/jdk/commit/a398fe4009ddf77578af49697c3f3a4211fc8adb
-- which incidentally I can upstream if you're interested!): If you
choose a non-nullable type argument, then it's on you to make sure that
the thing you're updating isn't set to `null` at construction time by
the default constructor (or at least that you'll be careful because
you're _aware_ that it's set to `null` at construction time).
(Under a Checker Framework approach, then, we would likely write
`<@Nullable V>` instead of `<V extends @Nullable Object>`.)
However, `AtomicReferenceFieldUpdater` adds _another_ wrinkle: If you
pick a _nullable_ type argument, then you are able to write `null` to a …
> Annotate `AtomicReferenceFieldUpdater`.

- src/java.base/share/classes/java/security/KeyStore.java
The class's Javadoc is inconsistent about documenting parameter
nullness: Sometimes it documents that a method throws NPE (or IAE...) if
parameter `foo` is null; sometimes it documents that parameter `bar` may
be null. Other times, it's silent :(
My defense of `@Nullable` here is:
- I see code inside Google that passes a literal `null` as the password.
- I even see code that does so inside the JDK:
https://github.com/openjdk/jdk/blob/4c2e54fb055bee0af5cd838fdd32a0f7902d51e3/src/java.base/share/classes/sun/security/tools/keytool/Main.java#L3812
- The code is implemented to [call
`engineGetKey`](https://github.com/jspecify/jdk/blob/7edfe499a1389be6dc445d173963489c27c71181/src/java.base/share/classes/java/security/KeyStore.java#L1061),
and at least [one implementation of that method …
> Permit a null `password` in `KeyStore.getKey`.

- src/java.base/share/classes/java/util/Observer.java
While there is no information about nullness in the docs for `Observer`
itself, we can find enough information in the docs for sibling class
`Observable`:
- [`notifyObservers()` is equivalent to
`notifyObservers(null)`.](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Observable.html#notifyObservers())
- [`notifyObservers(@Nullable Object arg)` calls `update`, passing `arg`
to
`Observer.update`.](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Observable.html#notifyObservers())
> Annotate the `arg` parameter of `Observer.update` as `@Nullable`.

- src/java.base/share/classes/java/lang/ThreadGroup.java
Since the method only writes to the array, it is fine with either a
nullable element type or a non-nullable element type. (I'm operating
under the usual assumption that tools treat arrays as covariant. For
purposes of Checker Framework users who set `-AinvariantArrays`, we
could consider using `@PolyNull` instead in eisop.)
This change is prompted by a Kotlin caller that passes an array of
`Thread?` because Kotlin won't allow an uninitialized array of `Thread`.
In Java, I would expect most users to allocate an uninitialized array of
`[@NonNull] Thread` and pass that.
(This is a pretty weird API, though, since it requires you to pass in an
array that you pre-size for the number of threads you expect and so you
might overshoot and end up (I assume; the docs are not clear) with nulls
in the …
> Make `enumerate` accept `@Nullable Thread[]` (ditto `ThreadGroup`).

- src/java.xml/share/classes/org/w3c/dom/Node.java
Compare https://github.com/jspecify/jdk/pull/24. The motivation is the
same as it was there (namely, Kotlin getter-setter pairs).
> Allow `Node.setTextContent` to be called with a null argument.

- src/java.base/share/classes/java/util/HashMap.java
- src/java.base/share/classes/java/util/Hashtable.java
- src/java.base/share/classes/java/util/Map.java
- src/java.base/share/classes/java/util/concurrent/ConcurrentHashMap.java
- src/java.base/share/classes/java/util/concurrent/ConcurrentMap.java
- src/java.base/share/classes/java/util/concurrent/ConcurrentSkipListMap.java
In contrast, for _`computeIfAbsent`_, I've kept the signature _without_
`@Nullable` on the function result type and method return type. This is
far more convenient for most callers, and it just might not cause
problems for anyone: Callers of `computeIfAbsent` might _always_ provide
a function that elects to insert a value (as expressed by returning a
non-null value).
I think this gives us the signatures that we'll want for the long term
for `Map`, though of course we'd revisit if we chose to include
`@PolyNull`.
Previously:
- https://github.com/jspecify/jdk/pull/14#issuecomment-1642254198
- https://github.com/jspecify/jdk/pull/19#issuecomment-1622173811
Note that this PR excludes `java.util.Properties` because there are a
number of other changes that I'm going to make to it (and then …
> Annotate `computeIfPresent` and `compute` more like the Checker Framework and Kotlin do.

- src/java.base/share/classes/java/util/Hashtable.java
- src/java.base/share/classes/java/util/Properties.java
I found my way to those classes as part of
https://github.com/jspecify/jdk/pull/32, but then I found other things
that looked wrong, even though the classes are annotated with
`@NullMarked.`
> Annotate `java.util.Properties` better (and `Hashtable` a little, too).

- src/java.base/share/classes/java/util/concurrent/ArrayBlockingQueue.java
- src/java.base/share/classes/java/util/concurrent/LinkedTransferQueue.java
- src/java.base/share/classes/java/util/concurrent/SynchronousQueue.java
- src/java.base/share/classes/java/util/concurrent/TransferQueue.java
A couple classes were not yet `@NullMarked`.
A couple others _were_ `@NullMarked` but were missing necessary
`@Nullable` annotations.
> Finish annotating the concurrent queues.

- src/java.base/share/classes/java/security/KeyStore.java
- `chain` is "only required if the given key is of type `PrivateKey`."
(OK, the 3-arg overload says "only _useful_ if the protected key is of
type `PrivateKey`" instead, but _surely_ it's fine, and I see
null-handling in some implementations of the
`KeyStoreSpi.engineSetKeyEntry` overload that it calls.)
- `password` is annoyingly unclear. You may recall
https://github.com/jspecify/jdk/pull/29... :) In this case, I can see
[a JDK call that passes the result of
`promptForKeyPass`](https://github.com/openjdk/jdk/blob/752121114f424d8e673ee8b7bb85f7705a82b9cc/src/java.base/share/classes/sun/security/tools/keytool/Main.java#L2041-L2056),
and I can see that [`promptForKeyPass` can return
`null`](https://github.com/openjdk/jdk/blob/752121114f424d8e673ee8b7bb85f7705a82b9cc/src/java.base/share/clas …
> Make `KeyStore.setKeyEntry` allow a null `password` and `chain`.

- src/java.base/share/classes/java/io/ObjectInput.java
- src/java.base/share/classes/java/io/ObjectInputStream.java
- src/java.base/share/classes/java/io/ObjectOutputStream.java
The docs are clear for the `ObjectInputFilter` methods but not for the
`read*` methods. It's definitely possible to serialize and deserialize
`null`, and _most_ of the methods in `ObjectOutputStream` are already
annotated to reflect this. `ObjectInputStream`, not so much.
> Add missing `@Nullable` annotations in serialization streams.

- src/java.base/share/classes/java/util/stream/Stream.java
See https://github.com/typetools/jdk/pull/177
(We already have the annotation on `ofNullable`, so we don't need to
carry that over.)
> Permit `flatMap*` function parameters to return a null stream.

- src/java.base/share/classes/java/util/zip/ZipEntry.java
I don't see an affirmative statement that `null` is allowed for
`setExtra` and `setComment`, but:
- They correspond to getters that can return `null`.
- Their implementations tolerate `null` (and, in one case, it goes
slightly out of its way to do so).
- They seem useful for clearing any undesired information that was
present from a `ZipEntry` cloned from an existing entry. (I saw them
being used with a literal `null` argument in a couple places, though
I'm not sure that any of those callers had a `ZipEntry` that actually
needed to be cleared.)
> Add missing `@Nullable` annotations in `ZipEntry`.

- src/java.base/share/classes/java/net/DatagramSocket.java
- src/java.base/share/classes/java/net/MulticastSocket.java
- src/java.base/share/classes/java/net/ServerSocket.java
- src/java.base/share/classes/java/net/Socket.java
- src/java.base/share/classes/java/net/SocketOption.java
Notes:
- `ServerSocket.setSocketFactory` "permits" `null` in the sense that
passing `null` is a no-op if no factory has been set yet. If a factory
has already been set, then passing `null` throws an exception. I
figure that that means it's best annotated as non-nullable, since it's
hard for me to imagine that anyone actually wants to pass `null`.
(Possibly there was another method similar to this one, either in this
PR or in another one? I forget.)
- The 2-arg `DatagramSocket` constructor says nothing about `null`. I
did find [a test that checks that users can pass `null` successfully](https://github.com/openjdk/jdk/blob/9559e035d2692d9d61bec2a13b5239a98db077ac/test/jdk/java/net/DatagramSocket/Constructor.java#L75),
though, and the handling of `null` seems in line with what we see in …
> Annotate `Socket` and related classes.

- src/java.base/share/classes/java/net/BindException.java
- src/java.base/share/classes/java/net/ConnectException.java
- src/java.base/share/classes/java/net/MalformedURLException.java
- src/java.base/share/classes/java/net/PortUnreachableException.java
- src/java.base/share/classes/java/net/ProtocolException.java
- src/java.base/share/classes/java/net/SocketException.java
- src/java.base/share/classes/java/net/UnknownServiceException.java
All of these have a no-arg constructor, so there is already a way to
create an instance with no message. Thus, letting users pass a null
message to the `(String)` constructor doesn't introduce any problems.
Compare https://github.com/eisop/jdk/pull/81.
> Annotate trivial `java.net` exceptions for nullness.

- src/java.base/share/classes/java/lang/reflect/Constructor.java
Compare
https://github.com/jspecify/jdk/commit/39c518822a63aa8655c55bb0b87695b92c70e8bd
for `Method.invoke`.
I'd stubbornly held on out `Constructor` because there's "no reason" to
ever pass a null array. That was purportedly in contrast to
`Method.invoke`, where you might naturally pass the same null array that
was provided to your implementation of `InvocationHandler`.
But then it occurred to me that, well, an `InvocationHandler` might
_also_ be written to call `Constructor.newInstance`, too. And sure
enough, I was able to find an example of that in Google's code.
It doesn't appear _common_. But I don't think my stubbornness here is
going to do anyone any good.
> `Constructor.newInstance`: Permit a null array of args.

- src/java.base/share/classes/java/util/Optional.java
Fixes https://github.com/jspecify/jspecify/issues/425
This takes us back to what we originally inherited from
[upstream](https://github.com/typetools/jdk/blob/7b360535a1f8ad40cb43326f63d9c0ecf2b630ab/src/java.base/share/classes/java/util/Optional.java#L415)
before I changed it in
https://github.com/jspecify/jdk/commit/d2ec17b2d678b968f710f94ac0477794948e004b.
> Annotate `orElseGet` as able to produce null values.

- src/java.base/share/classes/java/lang/reflect/AccessibleObject.java
https://github.com/typetools/jdk/pull/76 had added a `@CFComment` about
how it needs to be null in some cases, but naturally our autoconversion
script didn't know to change the annotations.
I should probably review the results of `git grep
'@CFComment.*nullness'` at the commit `autorewritten^` for any similar
required changes. (I did at least review the result of `git grep
'@CFComment[^:]*$'`, which didn't turn up anything new to do.)
> Annotate the parameter of `canAccess` as `@Nullable`.

- src/java.base/share/classes/java/lang/Class.java
They are unnecessary, troublesome, and probably wrong.
Unnecessary: We don't care about annotations on private and
package-private APIs because users don't interact with them. The only
reason that we have annotations here in the first place is that we we
automatically translated every occurrence of plain `<T>` to `<T extends
@Nullable Object>` in classes that were already annotated for nullness
in the upstream Checker Framework JDK. But that wasn't necessarily the
right thing to do for private and package-private members, since the
upstream Checker Framework JDK doesn't necessarily annotate those
properly (nor do we). So it's likely that the upstream code "should"
have used `<T extends [@NonNull] Object>`, which we would then have
automatically translated to `<T>`, thus avoiding this …
> Remove method-level `Atomic` annotations.

- src/java.base/share/classes/java/util/Arrays.java
- Add some `@Nullable` annotations for APIs added in Java 9.
- Add some `@Nullable` annotations for optional `Comparator` parameters.
- Remove some `@Nullable` annotations that I don't think are justified.
- [some on `sort` that were `@PolyNull`
upstream](https://github.com/typetools/jdk/commit/6630ac170c7c03f2b30414f1b329303df80bb22e#diff-51d93b3a0e9bcd89a7c9360d591f0bf77e9d72c93e00e9d071ce184bf1c0af4eL1057)
- some on `binarySearch` from way back in
https://github.com/typetools/jdk/commit/4d2993d87861d3b426bd6da87ffcc1c89c3cf337
> Improve annotations in `Arrays`:

- src/java.base/share/classes/java/util/IdentityHashMap.java
See https://github.com/typetools/jdk/pull/137
Eventually, we'll rebase onto the upstream stubs, at which point we'd
get this for free. But let's pick it up now.
> Add missing `@Nullable` annotation to `IdentityHashMap.equals`.

- src/java.base/share/classes/java/io/WriteAbortedException.java
- src/java.base/share/classes/java/util/ResourceBundle.java
- src/java.base/share/classes/jdk/internal/org/xml/sax/SAXException.java
- src/java.base/share/classes/sun/util/resources/Bundles.java
- src/java.management/share/classes/javax/management/remote/JMXProviderException.java
- src/java.naming/share/classes/javax/naming/NamingException.java
- src/java.rmi/share/classes/java/rmi/RemoteException.java
- src/java.rmi/share/classes/java/rmi/server/ServerCloneException.java
- src/java.security.sasl/share/classes/javax/security/sasl/SaslException.java
- src/java.xml.crypto/share/classes/javax/xml/crypto/KeySelectorException.java
- src/java.xml.crypto/share/classes/javax/xml/crypto/MarshalException.java
- src/java.xml.crypto/share/classes/javax/xml/crypto/NoSuchMechanismException.java
- src/java.xml.crypto/share/classes/javax/xml/crypto/URIReferenceException.java
- src/java.xml.crypto/share/classes/javax/xml/crypto/dsig/TransformException.java
- src/java.xml.crypto/share/classes/javax/xml/crypto/dsig/XMLSignatureException.java
- src/java.xml/share/classes/com/sun/org/apache/xalan/internal/xsltc/compiler/util/ErrorMsg.java
- src/java.xml/share/classes/com/sun/org/apache/xerces/internal/xni/XNIException.java
- src/java.xml/share/classes/javax/xml/stream/FactoryConfigurationError.java
- src/java.xml/share/classes/javax/xml/transform/TransformerException.java
- src/java.xml/share/classes/javax/xml/transform/TransformerFactoryConfigurationError.java
- src/java.xml/share/classes/javax/xml/xpath/XPathException.java
- src/java.xml/share/classes/org/xml/sax/SAXException.java
This started off as a cherry-pick of
https://github.com/typetools/jdk/commit/5816821ef4d977c60d699d8eec30d680e6139712.
Then I changed the annotations to JSpecify annotations.
Then found that a number of the changes in that commit appeared
questionable, so I reverted them. Specifically, for the following types,
it appears likely to me that the cause is never `null`:
- `TypeNotPresentExceptionProxy`
- `PrinterIOException`
- `MBeanException`
- `ReflectionException`
- `RuntimeErrorException`
- `RuntimeMBeanException`
- `RuntimeOperationsException`
- `JMXServerErrorException`
- `UncheckedDocletException`
> Improve annotations for `getCause()`.

- src/java.base/share/classes/java/lang/Thread.java
This matches `ThreadGroup.enumerate`, which `Thread.enumerate` calls.
My reading of https://github.com/jspecify/jdk/pull/28 is that I'd meant
to cover both classes then, but apparently I didn't.
(For the Checker Framework, we'll use `@PolyNull` instead, as we do for
`ThreadGroup`.)
Fixes https://github.com/jspecify/jdk/issues/61
> Annotate `Thread.enumerate` to accept arrays of nullable elements.

- src/java.base/share/classes/java/util/SequencedCollection.java
- src/java.base/share/classes/java/util/SequencedMap.java
- src/java.base/share/classes/java/util/SequencedSet.java
These stubs work around some problems we're seeing, and of course they
may let us identify actual problems in user code. They appear to cause
no problems in environments where the sequenced collections aren't yet
present (e.g., under JDK 11).
See
https://github.com/jspecify/jspecify-reference-checker/issues/192#issuecomment-2246251017
and elsewhere in that thread.
The files here are annotated copies of files from
https://github.com/openjdk/jdk/tree/476d2ae69d6f67fdf9e2a9353f224141318690f2.
Fixes https://github.com/jspecify/jspecify-reference-checker/issues/192.
> Add stubs for sequenced collections.

- src/java.base/share/classes/java/util/regex/MatchResult.java
(Compare the annotations to those on the subtype `Matcher`.)
> Annotate `MatchResult`, including JDK 20's `group(String)`.

- src/java.base/share/classes/java/lang/AbstractStringBuilder.java
- src/java.base/share/classes/java/lang/StringBuffer.java
- src/java.base/share/classes/java/lang/StringBuilder.java
I'm not sure that annotation in `AbstractStringBuilder` matter much, but
I'm not ruling it out that an expression could have that implicit type
if you wrote something like `b ? new StringBuilder() : new
StringBuffer()`. And anyway, it was nice to keep `AbstractStringBuilder`
up to date while having reference to its implementation so that I could
then easily cross-reference between it and the subclasses.
> Annotate the new `repeat` API on `StringBuilder` and friends.

- src/java.base/share/classes/java/util/jar/JarFile.java
This isn't a new API; we just missed this one.
> Add missing `@Nullable` annotation to `JarFile.getInputStream`.

- src/java.base/share/classes/java/util/Locale.java
This isn't a new API; we just missed this one.
> Add missing `@Nullable` annotation to `Locale.getExtension`.

- src/java.base/share/classes/java/lang/ScopedValue.java
I'm doing this entirely in response to an observation that this is a new
API that would benefit from `@PolyNull`:
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2147#issuecomment-1997570950
I haven't tried to annotate the rest of the class.
> Annotate `ScopedValue.orElse`.

- src/java.base/share/classes/java/lang/StackWalker.java
This builds on
https://github.com/typetools/jdk/commit/fd7576eb66877662b99e160e879ee3f27ca334cb.
I think that PR was actually unnecessary for Checker-Framework purposes
because type-parameter upper bounds default to `@Nullable` there, but we
do need such a change on the JSpecify side. This PR also adds a
`@Nullable` annotation to `StackFrame.getFileName()`.
> Annotate `StackWalker`.

- src/java.base/share/classes/java/util/concurrent/ConcurrentHashMap.java
It looks we just hadn't tried to annotate these yet. They do use `<T
extends @Nullable Object>` but only because that's what our
CF-stub-conversion tool produced from the `<T>` in the CF stubs; the
resulting unbounded type parameter doesn't seem to have been anyone's
conscious choice.
> Annotate the bulk methods of `ConcurrentHashMap`.

- src/java.base/share/classes/java/io/ObjectInputFilter.java
I looked at this class by accident when I was reviewing changes to
classes that are `@NullMarked`. (`ObjectInputFilter` is not.) Still,
since I saw a few places to add `@Nullable`, I'm doing that now, even as
I decline to fully null-mark the class.
> Opportunistically add a few `@Nullable` annotations to `ObjectInputFilter`.

- src/java.base/share/classes/java/lang/Class.java
We already do this for `getMethod`. In fairness, `getMethod` has clear
docs about it. These other methods do not. Still, I think that
`@Nullable` is justified, as I discussed in
https://github.com/jspecify/jdk/issues/96
Fixes https://github.com/jspecify/jdk/issues/96
> Accept a null array of parameter types for more methods.

- src/java.base/share/classes/java/util/Objects.java
The object returned by the supplier will be checked with `requireNonNull`.
> Allow the supplier to return null in `requireNonNullElseGet`.

- src/java.base/share/classes/java/util/Properties.java
This matches [what we have for
`Map.compute`](https://github.com/jspecify/jdk/blob/7cc2fbd5f404bf5403bd1375b47024a855838fef/src/java.base/share/classes/java/util/Map.java#L1247),
noting that `Properties` is a `Hashtable<Object, Object>` and so a
`Map<Object, Object>`.
See previous discussion in
https://github.com/jspecify/jdk/pull/114#discussion_r1888697414
> Mark the "previous value or `null`" type of `Properties.compute` as nullable.

- .github/workflows/jspecify.yml
I'm assuming that this will fix...
```
checking jtreg jar existence... checking jtreg version number... 7.5-dev
configure: error: jtreg version is too old, at least version 7.5.1 is required
```
https://github.com/jspecify/jdk/actions/runs/13930673343/job/38986758885
...from my merge of the upstream JDK branch. (Ideally we'd do that will
a pull request, which would then be properly tested, but GitHub doesn't
make that easy.)
Hopefully that's the only problem. CI will let us know.
And I'll have to test locally next time....
> Bump jtreg to 7.5.1.

- src/java.base/share/classes/java/util/concurrent/CompletionService.java
- src/java.base/share/classes/java/util/concurrent/ExecutorCompletionService.java
Compare
https://github.com/google/xplat/commit/9de0f2519f88b35f52a4128c707c356e4e948fb1
(which missed `@Nullable` on the `poll` methods, so I'll be fixing
that later).
> Annotate `CompletionService` classes.
